default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: ecg_load_scheduler_development


test:
  <<: *default
  database: ecg_load_scheduler_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
