default:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>


test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
